### PR TITLE
Fix/deal damage equal to block

### LINKED ISSUE #237: The Body Slam card doesn't work
### Discussed in https://github.com/oskarrough/slaytheweb/discussions/236

<div type='discussions-op-text'>

<sup>Originally posted by **luix10** May 16, 2024</sup>
Hello, cool project, congrats and thanks for sharing it!
The card Body Slam wasn't working and I managed to make it work by adding the property damage:0 in the card file, don't know if its a known bug but some other cards also don't have the damage property and works fine...</div>

It doesn't deal damage equal to block. If you add `damage: 0` to the card, it starts working.
If you have no block, and play the card, the card doesn't discard but keeps hanging.

### PR DESCRIPTION
**Pull request by oskarrough**
WIP, something is wrong the the nested immer produce logic.

Merge https://github.com/oskarrough/slaytheweb/pull/245 before this one.
Fixes #237

### CODE REVIEW

File: src/game/actions.js [hunk 1]
```diff
@@ -321,7 +324,7 @@ function addEnergyToPlayer(state, props) {
  * Removes health from a target, respecting vulnerable and block.
  * @type {ActionFn<{target: string, amount: number}>}
  */
-const removeHealth = (state, {target, amount}) => {
+const removeHealth = (state, {target, amount = 0}) => {
```
Comment (oskarrough) [inline src/game/actions.js:327]: this was the fix 🤷‍♂️

File: src/game/actions.js [hunk 2]
```diff
@@ -584,6 +587,9 @@ function dealDamageEqualToBlock(state, {target}) {
 	if (state.player.block) {
 		const block = state.player.block
 		return removeHealth(state, {target, amount: block})
+		getRoomTargets(state, target).forEach((t) => {
+
+		})
```
Comment (oskarrough) [inline src/game/actions.js:592]: remove
